### ISSUE TITLE
TypeError: scaled_dot_product_attention(): argument 'is_causal' must be bool, not Tensor

### ISSUE THREAD

**Issue by eschmidbauer** [NVIDIA-AI-IOT/whisper_trt#10]
trying to load `small.en`:

```
model = load_trt_model("small.en")
```

returns an exception

```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python3.10/site-packages/whisper_trt/model.py", line 422, in load_trt_model
    builder.build(path, verbose=verbose)
  File "python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "python3.10/site-packages/whisper_trt/model.py", line 312, in build
    "text_decoder_engine": cls.build_text_decoder_engine().state_dict(),
  File "python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "python3.10/site-packages/whisper_trt/model.py", line 206, in build_text_decoder_engine
    engine = torch2trt.torch2trt(
  File "python3.10/site-packages/torch2trt/torch2trt.py", line 608, in torch2trt
    torch.onnx.export(
  File "python3.10/site-packages/torch/onnx/utils.py", line 551, in export
    _export(
  File "python3.10/site-packages/torch/onnx/utils.py", line 1648, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "python3.10/site-packages/torch/onnx/utils.py", line 1170, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "python3.10/site-packages/torch/onnx/utils.py", line 1046, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "python3.10/site-packages/torch/onnx/utils.py", line 950, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "python3.10/site-packages/torch/jit/_trace.py", line 1497, in _get_trace_graph
    outs = ONNXTracedModule(
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "python3.10/site-packages/torch/jit/_trace.py", line 141, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "python3.10/site-packages/torch/jit/_trace.py", line 132, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "python3.10/site-packages/torch2trt/flatten_module.py", line 34, in forward
    output = self.module(*args)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "python3.10/site-packages/whisper_trt/model.py", line 94, in forward
    x = block(x, xa, mask)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "python3.10/site-packages/whisper/model.py", line 167, in forward
    x = x + self.attn(self.attn_ln(x), mask=mask, kv_cache=kv_cache)[0]
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "python3.10/site-packages/whisper/model.py", line 111, in forward
    wv, qk = self.qkv_attention(q, k, v, mask)
  File "python3.10/site-packages/whisper/model.py", line 124, in qkv_attention
    a = scaled_dot_product_attention(
TypeError: scaled_dot_product_attention(): argument 'is_causal' must be bool, not Tensor
```

**Comment by eschmidbauer** [comment]
i found the issue was related to the whisper version,
 `pip install openai-whisper==20240927`  solved it
